### ISSUE TITLE
OOT

### ISSUE THREAD

**Issue by adrianpuiu** [BillSchumacher/SumPAI#7]
you might wanna look here : https://huggingface.co/mosaicml/mpt-7b-storywriter ...  65K + tokens

**Comment by BillSchumacher** [comment]
Have you actually been able to run this? I haven't tried yet but I imagine a 65k context window is too much for my hardware to handle.

I was planning on increasing to GPT-4 and then GPT-4-32k but at this point you might consider refactoring your code before running it to save on costs.

**Comment by BillSchumacher** [comment]
This should be resolved now, assuming the context is less than 32k

**Comment by adrianpuiu** [comment]
I did managed to make it work in the text wui oogabooga or whatever its
called .
and modified the settings.json file lines 17 and 19 i think to 65k
and then launched it with : --model-menu --notebook --model
mosaicml_mpt-7b-storywriter --trust-remote-code
